(define (Inc x)(+ x 1))
(define (Dec x)(- x 1))
(define (pi)(* 4 (atan 1.0)))
(define (radian deg)(* deg(/ pi 180.0)))
(define (dx v t)(* v t))
(define (g)(9.8))
(define (ff-time vy)(/(* 2 vy) 9.8))
(define (distance v ang)
	(dx (* v (cos(radian ang)))
	(ff-time (* v (sin(radian ang))
	))))