(load "primer.scm")
(define (timed-primer-test n)
	(newline)
	(display n)
	(start-primer-test n (runtime)))
(define (start-primer-test n start-time)
	(if (primer n)
		(report-prime(- (runtime) start-time))))
(define (report-prime elapsed-time)
	(display "***")
	(display elapsed-time))